#name: Validate DNS Name Servers

on:
  schedule:
  - cron: "0 8/12 * * *"
  workflow_dispatch:

jobs:
  validate_dns_name_servers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous-resolvers.txt
        run: rm previous-resolvers.txt 2>/dev/null
        
        
      - name: Install dnsvalidator
        run: |
          git clone https://github.com/vortexau/dnsvalidator
          cd dnsvalidator
          sudo python3 setup.py install
          
          
      - name: Move previous resolvers.txt to previous-resolvers.txt
        run: mv resolvers.txt previous-resolvers.txt 2>/dev/null
  
  
      - name: Run dnsvalidator
        run: |
          cd dnsvalidator
          dnsvalidator -tL https://public-dns.info/nameservers.txt --silent -threads 12 >  ../resolvers.txt
          sort -u -o ../resolvers.txt ../resolvers.txt
          

      - name: Config git and push
        run: |
          git config --global user.name ${{ secrets.BOT_USERNAME }}
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git add resolvers.txt previous-resolvers.txt
          git commit -m "Update resolvers.txt using https://public-dns.info/nameservers.txt as source"
          git push
